### ISSUE TITLE
Detect controller hotplugging

### ISSUE THREAD

**Issue by Getterac7** [libgdx/libgdx#2182]
It would be nice to be able to listen for controller (joystick) connect and disconnect events so a user could add a controller and jump in during the middle of a game.

If that is not possible, maybe an API to scan for controller changes manually.

**Comment by Cevantime** [comment]
Hi, there. For now (1.5.3 libGdx version), it seems that the libGdx controller for desktop extension has not been rewritten yet. But it is easy to walk around this problem by using reflection. You just have to use relfection to reinstantiate the com.badlogic.gdx.controllers.desktop.DesktopControllerManager class in your app manager.
Here is a method you can use in your Game to reload controllers. 
```java
private Array<Controller> reloadControllers(){
	String controllersClassName = "com.badlogic.gdx.controllers.Controllers";
	try {
		//very hacky and dirty method to update controllers
		Class controllersClass = Class.forName(controllersClassName);
		Field managersField = controllersClass.getDeclaredField("managers");
		managersField.setAccessible(true);
		ObjectMap<Application, ControllerManager> managers = (ObjectMap<Application, ControllerManager>) managersField.get(null);
		managersField.setAccessible(false);
		String desktopControllerManagerClassName = "com.badlogic.gdx.controllers.desktop.DesktopControllerManager";
		managers.put(Gdx.app, (ControllerManager) Class.forName(desktopControllerManagerClassName).newInstance());

	} catch (ClassNotFoundException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	} catch (NoSuchFieldException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	} catch (SecurityException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IllegalArgumentException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		Logger.getLogger(Gamepad.class.getName()).log(Level.SEVERE, null, ex);
	}
	return Controllers.getControllers();
}
```
This is of course very dirty, but you're not supposed to invoke this method each time the render method is called (you better not!). Use a Timer for this : 
```java
@Override
public void create () {
        //... just add this at the end of your create method for instance
	if(Gdx.app.getType() == Application.ApplicationType.Desktop){
		Timer.schedule(new Timer.Task() {

			@Override
			public void run() {
				reloadControllers();
			}
		}, 0.5f, 0.5f);
	}
}
```

**Comment by bobbyrne01** [comment]
Would love this functionality. Want to avoid hacks that have been mentioned previously.

**Comment by TheSneakyNarwhal** [comment]
Same here. Listening for controller connects/disconnects without doing anything similar to the above would be great.

**Comment by badlogic** [comment]
This has been fixed in the new LWJGL 3 backend.

**Comment by the-coding-fox** [comment]
Can you explain how to get this working?
The connect() and disconnect() methods are not firing on desktop and I have the most recent version of libgdx.

**Comment by Cevantime** [comment]
You have to put the '1.7.3-SNAPSHOT' as gdxVersion in your build.gradle file. Then reload the project. In your DesktopLauncher class, you have to replace the regular LwjglApplicationConfiguration and LwjglApplication classes by the new Lwjgl**3**ApplicationConfiguration and Lwjgl**3**Application classes. The name of the controller manager is also different : Lwjgl3ControllerManager.
It's worth noting that you can't add listeners directly to your controllers. You'll have to add your listeners directly to an instance of Lwjgl3ControllerManager (and you'll have to declare the instance). 
```
Lwjgl3ControllerManager manager = new Lwjgl3ControllerManager();
manager.addListener(myListener);
```

**Comment by Jack5496** [comment]
Thanks, tired the dirty way, but lets see how this works

**Comment by Jack5496** [comment]
hmm still got an Error.
Chanced to '1.7.3.....' reloaded, took a small bit of time and had to reimport things but no problem,
but Eclipse still cant find class Lwjgl3ApplicationConfiguration

**Comment by Cevantime** [comment]
Okay, my mistake. I forgot to mention some other modifcations in the build.gradle file (I edited my previous post)

**Comment by the-coding-fox** [comment]
But the current GDX version is 1.9.0. How is it that I have to load 1.7.3-SNAPSHOT to get it working?

**Comment by the-coding-fox** [comment]
I followed the instructions from here: https://github.com/libgdx/libgdx/wiki/Controllers
> 
Simply check the "Controllers" checkbox in the gdx-setup app. For LWJGL 3, replace the dependency to gdx-controllers-desktop with gdx-controllers-lwjgl3 and remove the compile "com.badlogicgames.gdx:gdx-controllers-platform:$gdxVersion:natives-desktop" dependency in your desktop project.

It seems to load LWJGL3 just for the controller (which is better than loading it for the whole project), but I get an exception "Error creating controller manager: com.badlogic.gdx.controllers.desktop.DesktopControllerManager"

I did also test doing the changes you mentioned before, and I get the same problem. I would rather not change the whole project to LWJGL3 because it doesn't have the ability to set the window's icon.

**Comment by badlogic** [comment]
You will have to use the LWJGL 3 backend in connection with the LWJGL 3
controller backend.

**Comment by the-coding-fox** [comment]
I've tested using LWJGL3 for both the backend and the controller, the program runs now, but the disconnect() method still does not get called when I unplug the controller.

These are the dependencies I'm using for desktop. I've tried both 1.9.0 and 1.7.3-SNAPSHOT for the $gdxVersion.
```
    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-tools:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-lwjgl3:$gdxVersion"
    }
```

**Comment by badlogic** [comment]
What OS?

**Comment by the-coding-fox** [comment]
The device is using Windows 8.1

**Comment by CreamyCookie** [comment]
@the-coding-fox Is this still an issue?

**Comment by Cevantime** [comment]
As far as i know, lwjgl3 backend has not become the default implementation of lwjgl of libgdx yet (1.9.3 version). You still have to adapt your dependencies to make hotplugging work. I guess the issue will be quiet fixed when lwjgl3 will be default (and stable) and hotplugging working out of the box !

**Comment by fatalcubez** [comment]
So how can I get the lwjgl3 backend working for my libGDX project? I'm on version 1.9.3. I've tried changing the gradle build to include the lwjgl3 under desktop dependencies, but the controller api still fails to recognize that I have the lwjgl3 backend.

**Comment by CreamyCookie** [comment]
@fatalcubez Have you done everything here to enable lwjgl3: https://github.com/libgdx/libgdx/issues/3673

You also need to replace gdx-controllers-desktop with
gdx-controllers-lwjgl3 and remove the
compile "com.badlogicgames.gdx:gdx-controllers-platform:$gdxVersion:natives-desktop"
dependency in your desktop project.

**Comment by fatalcubez** [comment]
So I set everything up, but now I'm getting this exception:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Scott\AppData\Local\Temp\libgdxScott\68069333\lwjgl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
> 	at java.lang.Runtime.load0(Runtime.java:795)
> 	at java.lang.System.load(System.java:1062)
> 	at org.lwjgl.system.Library$1.load(Library.java:25)
> 	at org.lwjgl.system.Library$1.load(Library.java:22)
> 	at org.lwjgl.system.Library.loadLibrary(Library.java:196)
> 	at org.lwjgl.system.Library.loadSystem(Library.java:90)
> 	at org.lwjgl.system.Library.<clinit>(Library.java:48)
> 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56)
> 	at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:57)
> 	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:66)
> 	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:75)
> 	at com.fullspectrum.game.desktop.DesktopLauncher.main(DesktopLauncher.java:26)
> 

From what I've read about people who are having a similar issue but with different library dll files, the suggestion to change the JVM to be 32-bit. However, I was wondering if there is a fix for this so I can keep everything 64-bit. Thanks!

**Comment by fatalcubez** [comment]
For anyone who is wondering, it turns out that if you have the new lwjgl3 as well as the old lwjgl versions then you'll get this error. The source of my problem was that I was using gdx-tools which relies on the older lwjgl versions. Once I got rid of that in the gradle build and refreshed my project, the old lwjgl jars went away and the program ran without problem.
