### ISSUE TITLE
Crash on desktop (Music) Unable to allocate audio buffers

### ISSUE THREAD

**Issue by MateuszGawel** [libgdx/libgdx#2537]
I have no idea why it happens. I am getting "Unable to allocate audio buffers" exception. It's throwed from OpenALMusic.play().
Unfortunately I can't check what alGetError() returned because you are checking only if it has error or not. 

When it happens:
Only on desktop when I am switching between menu and game scene. Sometimes I have to switch few times, sometimes several times but it happens pretty randomly.

What I've found so far: 
-I don't use negative volume of the music
-I dispose music. The code fragment below is even more I need because I clear the manager after all but it still doesn't help. 

			Array<Music> tempMusicsListToStop = new Array<Music>();
			gameSpecialMeta.manager.getAll(Music.class, tempMusicsListToStop);	
			for(Music music : tempMusicsListToStop){
				music.stop();
				music.dispose();
			}
                        gameSpecialMeta.manager.clear();

It's called everytime in MenuScreen constructor.

What can be wrong? Is it possible that it's internal bug or something?

**Comment by badlogic** [comment]
I fixed @vaxquis issue best we can do. I will reopen this if we can reproduce it (compiling ApplicationListener that demos the issue).

**Comment by klianc09** [comment]
I'm having nearly the same problem, except for me it crashes reliably.
I can run the program without problems inside of IntelliJ, but when I package it for desktop and start the .jar the (first) music is distorted and when I try to load the second audio file it crashes with this exception: 
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeExcepti
on: Unable to allocate audio buffers.
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.ja
va:77) 
```

Since OP apparently doesn't want to have this fixed, I'll post a self-contained code example instead
```Java
public class AudioBugApp extends ApplicationAdapter {

    private static final String MUSIC_1 = "music/menu_music.wav";
    private static final String MUSIC_2 = "music/level_music.wav";

    @Override
    public void create () {
        play(MUSIC_1);

        Gdx.input.setInputProcessor(new InputAdapter(){
            @Override
            public boolean keyDown(int keycode) {
                //Press any key to crash the game
                play(MUSIC_2);
                return false;
            }
        });
    }

    private Music musicBeingPlayed;

    public void play(String music) {
        // stopAndDispose any music being played
        stopAndDispose();

        // start streaming the new music
        FileHandle musicFile = Gdx.files.internal(music);
        musicBeingPlayed = Gdx.audio.newMusic(musicFile);
        musicBeingPlayed.setVolume(1);
        musicBeingPlayed.setLooping(true);
        musicBeingPlayed.play();
    }

    /**
     * Stops and disposes the current music being played, if any.
     */
    public void stopAndDispose() {
        if (musicBeingPlayed != null) {
            musicBeingPlayed.stop();
            musicBeingPlayed.dispose();
            musicBeingPlayed = null;
        }
    }
}

```
I can also provide the audio files if needed, but GitHub only let's me add pictures to this comment so I would need to upload them to an external hoster.
I'm using Windows7 / 64 bit, and I first would have thought that it might be hardware-compatibility problems with OpenAL, but it DOES work in IntelliJ. It's only crashing on desktop.

**Comment by klianc09** [comment]
Ok, for anybody with the same problem as me, it seems like there are problems with .wav files with some hardware/version combinations of OpenAL... 
I __converted my .wav files to .ogg__ files (with Audacity) and suddenly the music works, even on desktop on my machine. I have no idea why and how this is exactly happening, but at least it's working now. (And the filesize is much smaller too!)

**Comment by MateuszGawel** [comment]
unfortunately I still have errors on desktop while using ogg. My main distribution channel would be Google Play so Android matters here but it's annoying when I have to develop my game without music while testing on desktop:)

**Comment by qnoox** [comment]
This is still a problem. my experience with this bug is that it has to do with the call to use the sound stream or what ever it's called. A rapid call triggers the crash. So if a sound is over used or a screen change happens with different sounds. In my mind this might be solved with some type of pooling solution. like you have for Particles. Might be a slight overkill. But maybe this idea triggers a better idea from someone else. The ball is in your court.

**Comment by NathanSweet** [comment]
What ball? "thing crashes sometimes"? SSCCE?

**Comment by qnoox** [comment]
It has a random crash pattern. it is the .play() that has some Buffer issue. as you can read from the error.
Feel free to ask for specific information. I'm happy to help with more "debug data"..

**Comment by Johnogel** [comment]
I'm not sure if this is going to help anyone, but I had a similar issue with my game crashing when play() was called on the Music object. I eventually figured out that my way of handling sound effects with the Sound interface was essentially eating up all of the memory. I had a short sound clip of fire (.wav) that I put on a loop. I used the Music interface instead for that specific sound and consolidated all Sound and Music instances to a SoundPlayer class that I created. My game hasn't crashed since! :)

All I can say is make sure all Sound AND Music objects are managed properly and dispose of them when necessary.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://studiehuset-fegu.dk/whisper.php?89fa>

 

loogie@basicelementdesign.com

**Comment by tomnom** [comment]
HI I GOT IT (mb just for me) if you try to play ANY type of sound after you dispose/or switched to a new screen in any way you will find this error. just make sure no sonds are playing (even the shortest ogg) after you commanded to switch screens/ dispose.

**Comment by MozB** [comment]
I also encountered this and found a different cause.

`setPosition()` to a position after the music ends will also cause this error.  Unfortunate because there isn't an (easy) way to determine the length of a music instance :)``

**Comment by xjcl** [comment]
Just had to open my mp3 in Audacity and re-export it as mp3. Must be some weird encoding issue.

**Comment by cebess** [comment]
I have had this happen when I added a fade out and then volume was set to less than zero. Once ensured the volume never went below zero -- things worked as expected.
