### ISSUE TITLE
Uncaught native exception from Controllers on OS X

### ISSUE THREAD

**Issue by matteblair** [libgdx/libgdx#2881]
If the LWJGL Application is not the active window when Controllers.initialize() is called, the application aborts from an uncaught exception in native code. 

The specific exception that occurs is here: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers-desktop/jni/ois-v1-4svn/src/mac/CocoaInputManager.mm#L88

Stack trace is here: http://pastebin.com/gNbiKiYv

gdx version 1.5.4
mac os 10.9.5
java 1.7.0_45

I can make a minimal reproducible test for this when I have some time, just wanted to save this before I forget about it!

**Comment by orangepascal** [comment]
Just ran into this same problem, with latest LibGDX 1.6.0.   Did not have this bug in older versions.
Also this bug only happens when I use Packr.jar on the file.  Without Packr, the bug doesn't happen on my system at least.

**Comment by NathanSweet** [comment]
FWIW, the Ois constructor calls createInputManager which crashes. Ois is called with OisControllers `getWindowHandle` which is always 0 for OS X. So it seems maybe the problem is in the native code.
`OIS::InputManager::createInputSystem`

**Comment by rafaskb** [comment]
A workaround that worked for me is only initiating ``Controllers`` when you're sure the window is active, which can be done through ``Display.isActive()``.

**Comment by BSVogler** [comment]
thanks @rafaskb. This fixed it for me!
(Java 1.8, GDX 1.8, Mac 10.11.2)

**Comment by code-disaster** [comment]
Fixed with https://github.com/libgdx/libgdx/commit/f49827f9e75e278852ca5368dc6a9d2cada24dc1

**Comment by code-disaster** [comment]
oh wow, sorry, not the same issue

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.

**Comment by matteblair** [comment]
Appreciate the follow-up on this old issue! The project that was running into this problem is no longer under active development, so I'm going to close this issue. If others are still experiencing the problem they should re-open it!
