### ISSUE TITLE
3d particles doesn't play nice with other transparent renderables

### ISSUE THREAD

**Issue by acatinon** [libgdx/libgdx#3742]
As you can see in the screenshot below, sometimes 3d particles are not draw behind semi transparent renderables. 

It seems that the particles renderable `worldTransform` field is never updated with the particles position. Therefore `DefaultRenderableSorter` can't sort the renderables properly and the particles aren't rendered when they are behind another renderable.

![screenshot](https://cloud.githubusercontent.com/assets/3535019/12379874/fb74c2ec-bd63-11e5-815d-415106425d8e.png)

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by jsjolund** [comment]
Here is an sscce which demonstrates the problem. It can be added to the g3d test programs, but you have to copy ```libgdx/extensions/gdx-tools/assets/defaultTemplate.pfx``` to ```libgdx/tests/gdx-tests-android/assets/data/defaultTemplate.pfx``` first.

The problem is as @acatinon says - ```Renderable#worldTransform``` is never updated in e.g. ```BillboardParticleBatch#getRenderables(Array<Renderable> renderables, Pool<Renderable> pool)``` (similar for the other types of particle batches).

For the billboards, this can probably be fixed by modifying ```BillboardParticleBatch``` to use a separate ```Renderable``` for each ```ParticleController```, then update ```Renderable#worldTransform``` to the correct value. This means it can be sorted correctly by ```DefaultRenderableSorter``` before being rendered. It will require some major refactoring of the methods ```flush```, ```fillVerticesToViewPointCPU```, ```fillVerticesToScreenCPU```, ```fillVerticesGPU``` and others in ```BillboardParticleBatch```. Right now, all ```ParticleController```s are dumped into the least amount of ```Renderable```s needed to contain the particles, without regard to their transforms. This was probably done for optimization purposes, but creates problems when sorting before rendering.

One problem with the solution of updating ```Renderable#worldTransform``` is that ```BillboardParticleBatch``` calculates the vertices in world coordinates internally, without relying on the vertices being multiplied by ```worldTransform``` matrix (unlike e.g. ModelInstance). So setting ```Renderable#worldTransform``` will multiply the vertices (which are already in world space) by another world space transform matrix (this happens in the shader I think). This will mess things up greatly, but can probably be worked around.

I have not checked if this is a problem for ```ModelInstanceParticleBatch``` and ```PointSpriteParticleBatch``` yet, nor how to fix the problem if it exists.

```
package com.badlogic.gdx.tests.g3d;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.attributes.BlendingAttribute;
import com.badlogic.gdx.graphics.g3d.particles.ParticleEffect;
import com.badlogic.gdx.graphics.g3d.particles.ParticleShader;
import com.badlogic.gdx.graphics.g3d.particles.ParticleSystem;
import com.badlogic.gdx.graphics.g3d.particles.batches.BillboardParticleBatch;
import com.badlogic.gdx.graphics.g3d.particles.batches.ModelInstanceParticleBatch;
import com.badlogic.gdx.graphics.g3d.particles.batches.PointSpriteParticleBatch;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.utils.Array;

public class ParticleSystemAlphaTest extends BaseG3dTest {

	static final String EFFECT = "data/defaultTemplate.pfx";
	static final String PARTICLE = "data/pre_particle.png";
	static final String MODEL = "data/cube.obj";
	ParticleSystem particleSystem = ParticleSystem.get();
	ParticleEffect effect;
	BillboardParticleBatch billboardParticleBatch;
	ModelInstanceParticleBatch modelInstanceParticleBatch;
	PointSpriteParticleBatch pointSpriteParticleBatch;

	@Override
	public void create () {
		super.create();

		modelInstanceParticleBatch = new ModelInstanceParticleBatch();

		pointSpriteParticleBatch = new PointSpriteParticleBatch();
		pointSpriteParticleBatch.setCamera(cam);

		billboardParticleBatch = new BillboardParticleBatch();
		billboardParticleBatch.setCamera(cam);
		billboardParticleBatch.setUseGpu(false);
		billboardParticleBatch.setAlignMode(ParticleShader.AlignMode.Screen);
		
		particleSystem.add(modelInstanceParticleBatch);
		particleSystem.add(billboardParticleBatch);
		particleSystem.add(pointSpriteParticleBatch);
		
		assets.load(MODEL, Model.class);
		assets.load(PARTICLE, Texture.class);
		assets.load(EFFECT, ParticleEffect.class);
		
		loading = true;
	}

	@Override
	protected void onLoaded () {
		pointSpriteParticleBatch.setTexture(assets.get(PARTICLE, Texture.class));
		billboardParticleBatch.setTexture(assets.get(PARTICLE, Texture.class));

		effect = assets.get(EFFECT, ParticleEffect.class).copy();
		effect.translate(new Vector3(-7,0,-7));
		effect.init();
		effect.start();
		effect.setBatch(particleSystem.getBatches());

		particleSystem.add(effect);
		
		ModelInstance modelInstance = new ModelInstance(assets.get(MODEL, Model.class));
		modelInstance.materials.first().set(new BlendingAttribute(0.5f));
		modelInstance.transform.setTranslation(-5,0,-5);
		instances.add(modelInstance);
	}

	@Override
	protected void render (ModelBatch batch, Array<ModelInstance> instances) {
		particleSystem.update();
		particleSystem.begin();
		particleSystem.draw();
		particleSystem.end();
		batch.render(particleSystem);
		for (ModelInstance instance : instances)
			batch.render(instance);
	}

	@Override
	public void dispose () {
		super.dispose();
		effect.dispose();
	}
}

```

**Comment by yuripourre** [comment]
Hi, @acatinon , can you confirm if it was fixed with the lastest commit? Sep 7?

**Comment by acatinon** [comment]
Woow I don't even know if I still have the corresponding code! I think this can be closed.

**Comment by yuripourre** [comment]
@MrStahlfelge Hello, can you close this, please?
