### ISSUE TITLE
AssetManager: NullPointerException vs isLoaded => true ~ unload() called twice

### ISSUE THREAD

**Issue by j3nda** [libgdx/libgdx#5929]
Please ensure you have given all the following requested information in your report.

#### Issue details
when AssetManager try to unload same resource twice it will fail on NullPointerException, here:
```java
		// get the asset and its type
		Class type = assetTypes.get(fileName);
		if (type == null) throw new GdxRuntimeException("Asset not loaded: " + fileName);

		RefCountedContainer assetRef = assets.get(type).get(fileName); // <<< NullPointerException

		// if it is reference counted, decrement ref count and check if we can really get rid of it.
		assetRef.decRefCount();
```

- on 1st attempt, when resource is loaded: assetManager.isLoaded(resourceName) will return true; and then assetManager.unload(resourceName); is OK!

but

- on 2nd attemt, resource is already unloaded and: somehow assetManager.isLoaded(resourceName) returns TRUE instead of false! so mine code will call again: 
assetManager.unload(resourceName) ~ because it says its loaded, so: next pass is failing on NullPointerException: "RefCountedContainer assetRef = assets.get(type).get(fileName);"
where first get(type) is positive - but second one get(fileName) will return null!

#### Reproduction steps/code
v1.9.10:
1) assetManager.load(any TextureAtlas);
2) ask for isLoaded(textureAtlasName) => true;
3) so unload(TextureAtlasName); => OK
4) ask again for isLoaded(textureAtlasName) => false; <<< OK
5) so unload(TextureAtlasName); => GdxRuntimeException("Asset not loaded: " + fileName); <<< OK

v1.9.11-SNAPSHOT ~ 2020-03-01
1) assetManager.load(any TextureAtlas);
2) ask for isLoaded(textureAtlasName) => true;
3) so unload(TextureAtlasName); => OK
4) ask again for isLoaded(textureAtlasName) => true; <<< BUG
5) so unload(TextureAtlasName); => NullPointerException <<< BUG

#### Version of LibGDX and/or relevant dependencies
1.9.11-SNAPSHOT (v.1.9.10 is ok)

#### Stacktrace
```java
| 2020/03/01 21:09:46.103 |  ERROR  | Current screen: com.sjet.gula.graphics.screens.singleplayer.SingleplayerGameScreen                                                                               [ WorldOfClonesGame.java:343 ]
| 2020/03/01 21:09:46.104 |  ERROR  | Application detected fatal exception!                                                                                                                            [ WorldOfClonesGame.java:344 ]
Exception:java.lang.NullPointerException
com.badlogic.gdx.assets.AssetManager.unload(AssetManager.java:237)
com.sjet.gula.resources.dynamic.DynamicResourcesManager.unloadGroupTextures(DynamicResourcesManager.java:579)
com.sjet.gula.resources.dynamic.DynamicResourcesManager.unloadGroup(DynamicResourcesManager.java:553)
com.sjet.gula.resources.ResourcesManager.unloadGroup(ResourcesManager.java:361)
com.sjet.gula.graphics.screens.ScreenBase.unloadScreenResources(ScreenBase.java:252)
com.sjet.gula.graphics.screens.ScreenBase.hide(ScreenBase.java:168)
com.sjet.gula.graphics.screens.GameScreenBase.hide(GameScreenBase.java:686)
com.badlogic.gdx.Game.setScreen(Game.java:58)
com.sjet.gula.WorldOfClonesGame.setScreen(WorldOfClonesGame.java:389)
com.sjet.gula.graphics.screens.GameScreenBase.redirectToNextScreen(GameScreenBase.java:458)
com.sjet.gula.graphics.screens.GameScreenBase.onUserAnswered(GameScreenBase.java:640)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog.fireUserAnswered(YesOrNoDialog.java:59)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog$1.changed(YesOrNoDialog.java:156)
com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:189)
com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:153)
com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:95)
com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:60)
com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
com.badlogic.gdx.backends.lwjgl.GulaDesktopLWJGLApp.mainLoop(GulaDesktopLWJGLApp.java:121)
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
[__RETURN_CODE__] 2
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: graphics/units/bellis/attack.png
	at com.badlogic.gdx.assets.AssetManager.unload(AssetManager.java:232)
	at com.badlogic.gdx.assets.AssetManager.clear(AssetManager.java:725)
	at com.badlogic.gdx.assets.AssetManager.dispose(AssetManager.java:693)
	at com.sjet.gula.resources.ResourcesManager.dispose(ResourcesManager.java:179)
	at com.sjet.gula.WorldOfClonesGame.dispose(WorldOfClonesGame.java:411)
	at com.badlogic.gdx.backends.lwjgl.GulaDesktopLWJGLApp.mainLoop(GulaDesktopLWJGLApp.java:162)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

#### EXAMPLE ~ which fails (on 1.9.11-SNAPSHOT) and 1.9.10 is ok
(focus on part around: "if (Version.isLower(1, 9, 11))" else ...
```java|
	private void unloadGroupAnimations(Array<String> resources)
	{
		if (resources == null)
		{
			return;
		}
		for (String resource : resources)
		{
			AnimationConfiguration animationConfig = configLoader.getAnimationConfiguration(resource);
			boolean isFreezed = freezeToUnloadResources.contains(animationConfig.getTextureAtlas());
			boolean isLoaded = assetManager.isLoaded(animationConfig.getTextureAtlas());
			logger.debug(
				"unload(animation)["
				+ (isFreezed ? "F" : "-")
				+ (isLoaded  ? "L" : "-")
				+ "]:"
				+ resource
			);
			isFreezed = false;
			if (!isFreezed && isLoaded)
			{
				if (animationConfig.getTextureAtlas() != null)
				{
					if (Version.isLower(1, 9, 11))
					{
						assetManager.unload(animationConfig.getTextureAtlas());
					}
					else
					{
						// because v1.9.10 is ok (~but contains AnimatedTile bug) and 1.9.11-SNAPSHOT has this
						// weird behavior...
						try
						{
							assetManager.unload(animationConfig.getTextureAtlas());
						}
						catch(Exception e)
						{
							// im just ignoring it...
							// it's because unload is async! and there isnt any callback, when its finished!
							// eg: unload:
							// - graphics/units/gribs/run_left.json
							// - graphics/units/gribs/run_right.json
							//
							// its using same TextureAtlas ~ "graphics/units/gribs/run.atlas" and
							// 1st unload() will create async task to unload it. and do it!
							// 2nd unload() will report, that resource is loaded(true) ~ so this will fail!
							//
							// its happening inside: AssetManager.unload(), at:
							// RefCountedContainer assetRef = assets.get(type).get(fileName);
System.out.println(e);
						}
					}
				}
				onUnloadListeners.onUnloadResourceAnimation(animationConfig);
			}
		}
	}
```

```
| 2020/03/01 21:30:25.568 |  DEBUG  | unload(animation)[-L]:graphics/units/gribs/die_left.json                                                                                                         [ Logger.java:142 ]
| 2020/03/01 21:30:25.568 |  DEBUG  | unload(animation)[-L]:graphics/units/gribs/die_right.json                                                                                                        [ Logger.java:142 ]
| 2020/03/01 21:30:25.569 |  DEBUG  | unload(animation)[-L]:graphics/units/gribs/run_left.json                                                                                                         [ Logger.java:142 ]
java.lang.NullPointerException
| 2020/03/01 21:32:22.823 |  DEBUG  | unload(animation)[-L]:graphics/units/gribs/run_right.json                                                                                                        [ Logger.java:142 ]
java.lang.NullPointerException
| 2020/03/01 21:32:33.615 |  DEBUG  | unload(animation)[-L]:graphics/units/kingofanimals/attack_left.json                                                                                              [ Logger.java:142 ]
| 2020/03/01 21:32:33.616 |  DEBUG  | unload(animation)[-L]:graphics/units/kingofanimals/attack_right.json                                                                                             [ Logger.java:142 ]
| 2020/03/01 21:32:33.618 |  DEBUG  | unload(animation)[-L]:graphics/units/kingofanimals/die_left.json                                                                                                 [ Logger.java:142 ]
| 2020/03/01 21:32:33.619 |  DEBUG  | unload(animation)[-L]:graphics/units/kingofanimals/die_right.json                                                                                                [ Logger.java:142 ]
| 2020/03/01 21:32:33.621 |  DEBUG  | unload(animation)[-L]:graphics/units/kingofanimals/run_left.json 
```

**Comment by j3nda** [comment]
well ~ the behavior is still weird. even if im by-passing it, it will fail on ObjectMap (se below)

maybe isnt bug in AssetManager (~its just triggers that)
what im doing (~by mine DynamicResourcesManager) im loading and unloading required Screen's resources. and this is happening after by-passing unload() in next screen which is AssetManager.load() resources

```java
...
Caused by: 
Exception:java.lang.IllegalArgumentException
key cannot be null.
com.badlogic.gdx.utils.ObjectMap.locateKey(ObjectMap.java:128)
com.badlogic.gdx.utils.ObjectMap.get(ObjectMap.java:179)
com.badlogic.gdx.assets.AssetManager.incrementRefCountedDependencies(AssetManager.java:607)
```

```java
| 2020/03/01 21:53:21.870 |  ERROR  | Current screen: com.sjet.gula.graphics.screens.singleplayer.WinLoseScreen                                                                                        [ WorldOfClonesGame.java:343 ]
| 2020/03/01 21:53:21.870 |  ERROR  | Application detected fatal exception!                                                                                                                            [ WorldOfClonesGame.java:344 ]
Exception:com.badlogic.gdx.utils.GdxRuntimeException
java.lang.IllegalArgumentException: key cannot be null.
com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:618)
com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:412)
com.sjet.gula.resources.ResourcesManager.update(ResourcesManager.java:446)
com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:439)
com.sjet.gula.graphics.screens.singleplayer.WinLoseScreen.loadScreenResources(WinLoseScreen.java:969)
com.sjet.gula.graphics.screens.ScreenBase.show(ScreenBase.java:202)
com.sjet.gula.graphics.screens.singleplayer.WinLoseScreen.show(WinLoseScreen.java:770)
com.badlogic.gdx.Game.setScreen(Game.java:61)
com.sjet.gula.WorldOfClonesGame.setScreen(WorldOfClonesGame.java:389)
com.sjet.gula.graphics.screens.GameScreenBase.redirectToNextScreen(GameScreenBase.java:458)
com.sjet.gula.graphics.screens.GameScreenBase.onUserAnswered(GameScreenBase.java:640)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog.fireUserAnswered(YesOrNoDialog.java:59)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog$1.changed(YesOrNoDialog.java:156)
com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:189)
com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:153)
com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:95)
com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:60)
com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
com.badlogic.gdx.backends.lwjgl.GulaDesktopLWJGLApp.mainLoop(GulaDesktopLWJGLApp.java:121)
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: 
Exception:java.lang.IllegalArgumentException
key cannot be null.
com.badlogic.gdx.utils.ObjectMap.locateKey(ObjectMap.java:128)
com.badlogic.gdx.utils.ObjectMap.get(ObjectMap.java:179)
com.badlogic.gdx.assets.AssetManager.incrementRefCountedDependencies(AssetManager.java:607)
com.badlogic.gdx.assets.AssetManager.nextTask(AssetManager.java:521)
com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:405)
com.sjet.gula.resources.ResourcesManager.update(ResourcesManager.java:446)
com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:439)
com.sjet.gula.graphics.screens.singleplayer.WinLoseScreen.loadScreenResources(WinLoseScreen.java:969)
com.sjet.gula.graphics.screens.ScreenBase.show(ScreenBase.java:202)
com.sjet.gula.graphics.screens.singleplayer.WinLoseScreen.show(WinLoseScreen.java:770)
com.badlogic.gdx.Game.setScreen(Game.java:61)
com.sjet.gula.WorldOfClonesGame.setScreen(WorldOfClonesGame.java:389)
com.sjet.gula.graphics.screens.GameScreenBase.redirectToNextScreen(GameScreenBase.java:458)
com.sjet.gula.graphics.screens.GameScreenBase.onUserAnswered(GameScreenBase.java:640)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog.fireUserAnswered(YesOrNoDialog.java:59)
com.sjet.gula.graphics.ui.items.dialogs.YesOrNoDialog$1.changed(YesOrNoDialog.java:156)
com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:189)
com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:153)
com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:95)
com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:60)
com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
com.badlogic.gdx.backends.lwjgl.GulaDesktopLWJGLApp.mainLoop(GulaDesktopLWJGLApp.java:121)
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
[__RETURN_CODE__] 2
```

**Comment by j3nda** [comment]
ok, if im by-passing even: AssetManager.update() to load resources

```java
public class ResourcesManager
extends AssetManager
...
	public synchronized boolean update()
	{
//		boolean finished = super.update();
		boolean finished = update_byPassToBuggyLibGdx_v1_9_11();
		if (finished)
		{
			dynamicResourcesManager.onLoadAllResources(this);
		}
		return finished;
	}

	private synchronized boolean update_byPassToBuggyLibGdx_v1_9_11()
	{
		if (Version.isLower(1, 9, 11))
		{
			return super.update();
		}
		else
		{
			// because v1.9.10 is ok (~but contains AnimatedTile bug) and 1.9.11-SNAPSHOT has this
			// weird behavior...
			try
			{
				return super.update();
			}
			catch(Exception e)
			{
				logger.debug("update(ERROR): " + e.getMessage());
				logger.error(e.toString());
				return false;
			}
		}
	}
```

and in Screen's is code like: 
```java
public class WinLoseScreen
implements Screen
{
...
	@Override
	protected void loadScreenResources()
	{
		super.loadScreenResources(); // <<< HERE is using: AssetManager.load(resourceName, Class<?>);
		resources.finishLoading();
	}
```

it will've this output:
```java
| 2020/03/01 22:10:58.459 |  DEBUG  | load(texture)[L]: graphics/ui/ui-game.atlas                                                                                                                      [ Logger.java:142 ]
| 2020/03/01 22:10:58.459 |  DEBUG  | load(texture)[L]: graphics/backgrounds/errors.atlas                                                                                                              [ Logger.java:142 ]
| 2020/03/01 22:10:58.460 |  DEBUG  | load(texture)[L]: graphics/backgrounds/misc.atlas                                                                                                                [ Logger.java:142 ]
| 2020/03/01 22:10:58.460 |  DEBUG  | load(animation)[L]: graphics/ui/misc/camp_arrow_animation.json                                                                                                   [ Logger.java:142 ]
| 2020/03/01 22:10:58.461 |  DEBUG  | load(animation)[L]: graphics/ui/misc/level_up_animation.json                                                                                                     [ Logger.java:142 ]
| 2020/03/01 22:10:58.461 |  DEBUG  | load(animation)[-]: graphics/ui/misc/minimap_warning.json                                                                                                        [ Logger.java:142 ]
| 2020/03/01 22:10:58.462 |  DEBUG  | load(animation)[L]: graphics/ui/misc/repair_building_animation.json                                                                                              [ Logger.java:142 ]
| 2020/03/01 22:10:58.466 |  DEBUG  | load(group): done: [Shared]                                                                                                                                      [ Logger.java:142 ]
| 2020/03/01 22:10:58.467 |  DEBUG  | update(ERROR): java.lang.IllegalArgumentException: key cannot be null.                                                                                           [ Logger.java:142 ]
| 2020/03/01 22:10:58.467 |  ERROR  | com.badlogic.gdx.utils.GdxRuntimeException: java.lang.IllegalArgumentException: key cannot be null.  
```

**Comment by mgsx-dev** [comment]
1.9.11-SNAPSHOT (Sun Mar 01 2020 00:25:11 GMT+0100 (Central European Standard Time)) works:
```
AssetManager am = new AssetManager();
am.load(name, TextureAtlas.class);
am.finishLoading();
System.out.println(am.isLoaded(name));
am.unload(name);
System.out.println(am.isLoaded(name));
```
outputs true/false as expected.

Are you sure you're using latest snapshot as me? there was a [commit fixing ObjectMap and friends](Sun Mar 01 2020 00:25:11 GMT+0100 (Central European Standard Time)) yesterday, maybe it's related.

**Comment by tommyettinger** [comment]
It doesn't look like a change in ObjectMap; it has never allowed null keys and that's what the current exception is about. On [AssetManager line 607](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/AssetManager.java#L607), there are two calls to ObjectMap.get(); only the first might have a null key because `dependency` has already been used to look up a value on line 606. It's possible that **before** the latest ObjectMap change (which almost entirely affected `containsValue()` and `findKey()`), some code in AssetManager was incorrectly reporting no value was found when it really was present; this should be fixed as of yesterday.

**Comment by j3nda** [comment]
thx guys. i will re-check it with current snapshot (~and if its still there i will prepare example)

**Comment by j3nda** [comment]
yes, the problem is still there (~even on fresh 1.9.11-SNAPSHOT; 2020-03-03 21:29 CET)
and its ObjectMap related.
```
| 2020/03/03 21:28:35.558 |  DEBUG  | update(ERROR): update_byPassToBuggyLibGdx_v1_9_11: java.lang.IllegalArgumentException: key cannot be null.                                                       [ Logger.java:142 ]
| 2020/03/03 21:28:35.559 |  ERROR  | com.badlogic.gdx.utils.GdxRuntimeException: java.lang.IllegalArgumentException: key cannot be null.                                                              [ ResourcesManager.java:506 ]
| 2020/03/03 21:28:36.362 |  DEBUG  | Switching from screen GAME_WIN_LOSE_SCREEN to SKIRMISH_SCREEN     
```

**Comment by tommyettinger** [comment]
I submitted a PR that might fix this, #5932 , above. The PR is meant to addresses a case where put() and remove() are called in a mixed order; that is probably what is happening here and would explain unexpected null results. If #5932 doesn't fix this issue, it's going to take more in-depth stepping through AssetManager to find where things go wrong.

**Comment by NathanSweet** [comment]
#5932 has been merged, please confirm this issue is fixed.

**Comment by tommyettinger** [comment]
Well, we may need to wait until a nightly builds. It shouldn't be long, right? And anyone can check at [the Nexus snapshot folder](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/badlogicgames/gdx/gdx/1.9.11-SNAPSHOT/) (ctrl-f 202003 to find anything in March of this year) if they are curious which nightly they got.

**Comment by j3nda** [comment]
confirm #5932 fixes this problem
