### ISSUE TITLE
ios module build error, empty project without any code changes

### ISSUE THREAD

**Issue by ebnbin** [libgdx/libgdx#6884]
#### Issue details

I generated an empty project with the latest gdx-setup.jar without any code changes, then run ios module with the following errors.

#### Version of libGDX and/or relevant dependencies

```
MD5 (gdx-setup.jar) = 00f1f8c2514121507143712d058b9977
```

```
MacBook Pro (Apple M1 Pro)
```

```
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 11, 2022
```

```
gdxVersion = '1.11.0'
roboVMVersion = '2.3.16'
```

```
gradle wrapper version: 7.3.3
```

```
MobiVM idea plugin version: 2.3.16
```

#### Stacktrace

RoboVM console log:

```
[INFO] 10:59:20.940 RoboVM plugin initialized
[INFO] 11:01:01.005 Loading default RoboVM config properties file: /Users/ebnbin/Downloads/test/ios/robovm.properties
[INFO] 11:01:01.005 Loading default RoboVM config file: /Users/ebnbin/Downloads/test/ios/robovm.xml
[INFO] 11:01:01.007 Building executable in /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 11:01:01.007 Installation of app in /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/Downloads/test/core/build/classes/java/main
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/Downloads/test/ios/build/classes/java/main
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-robovm/1.11.0/bedda1c3f9ecf153a9edd245831e620371614d64/gdx-backend-robovm-1.11.0.jar
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.11.0/ffe1206d1004cd9e40027e28964be0fea0399af7/gdx-1.11.0.jar
[INFO] 11:01:01.009 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-jnigen-loader/2.3.1/2d472f69243631fbcb3d4c3f93dd2e137a6cb084/gdx-jnigen-loader-2.3.1.jar
[INFO] 11:01:01.009 Using SDK boot classpath
[INFO] 11:01:01.148 Cleaning output dir /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 11:01:01.175 Compiling classes using 10 threads
[INFO] 11:01:01.310 Compiling com.mygdx.game.IOSLauncher (ios arm64-simulator release)
[INFO] 11:01:01.623 Compiling com.mygdx.game.MyGdxGame (ios arm64-simulator release)
[INFO] 11:01:03.059 Compiled 2 classes in 1.88 seconds
[INFO] 11:01:03.061 Linking 4371 classes (ios arm64-simulator release)
[INFO] 11:01:03.178 50905 methods out of 51391 included in the executable
[INFO] 11:01:04.814 Building ios binary /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher
[INFO] 11:01:04.821 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher -Wl,-filelist,/Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/objects0 -w -L /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator -ObjC -exported_symbols_list /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC --target=arm64-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/Entitlements-Simulated.plist -lrobovm-bc -force_load /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework UIKit -framework QuartzCore -framework CoreGraphics -framework OpenAL -framework AudioToolbox -framework AVFoundation -framework GameController -force_load /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator/libgdx.a -force_load /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator/libObjectAL.a -lz -framework MobileCoreServices -Xlinker -sdk_version -Xlinker 15.5 -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath 
[INFO] 11:01:04.821     -Xlinker @loader_path/Frameworks
[ERROR] 11:01:05.448 Undefined symbols for architecture arm64:
[ERROR] 11:01:05.448   "_glInvalidateFramebuffer", referenced from:
[ERROR] 11:01:05.448       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateFramebuffer in libgdx.a(iosgl30.o)
[ERROR] 11:01:05.517      (maybe you meant: _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateFramebuffer__IILjava_nio_IntBuffer_2, _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateFramebuffer , _str_glInvalidateFramebuffer_00 )
[ERROR] 11:01:05.517   "_glProgramParameteri", referenced from:
[ERROR] 11:01:05.517       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glProgramParameteri in libgdx.a(iosgl30.o)
[ERROR] 11:01:05.586      (maybe you meant: _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glProgramParameteri, _str_glProgramParameteri_00 , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glProgramParameteri__III )
[ERROR] 11:01:05.586   "_glResumeTransformFeedback", referenced from:
[ERROR] 11:01:05.586       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glResumeTransformFeedback in libgdx.a(iosgl30.o)
[ERROR] 11:01:05.655      (maybe you meant: _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glResumeTransformFeedback__, _str_glResumeTransformFeedback_00 , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glResumeTransformFeedback )
[ERROR] 11:01:05.655   "_glPauseTransformFeedback", referenced from:
[ERROR] 11:01:05.655       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glPauseTransformFeedback in libgdx.a(iosgl30.o)
[ERROR] 11:01:05.745      (maybe you meant: _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glPauseTransformFeedback, _str_glPauseTransformFeedback_00 , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glPauseTransformFeedback__ )


// ...
// too long...
// ...


[ERROR] 11:01:21.867   "_glFramebufferTexture2D", referenced from:
[ERROR] 11:01:21.868       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glFramebufferTexture2D in libgdx.a(iosgl20.o)
[ERROR] 11:01:21.946      (maybe you meant: _str_glFramebufferTexture2D_00, _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glFramebufferTexture2D , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glFramebufferTexture2D__IIIII )
[ERROR] 11:01:21.946   "_glGenQueries", referenced from:
[ERROR] 11:01:21.946       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glGenQueries__I_3II in libgdx.a(iosgl30.o)
[ERROR] 11:01:21.946       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glGenQueries__ILjava_nio_IntBuffer_2 in libgdx.a(iosgl30.o)
[ERROR] 11:01:22.029      (maybe you meant: _str_glGenQueries_00, _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glGenQueries__I_3II , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glGenQueries__ILjava_nio_IntBuffer_2 )
[ERROR] 11:01:22.029   "_glInvalidateSubFramebuffer", referenced from:
[ERROR] 11:01:22.029       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateSubFramebuffer in libgdx.a(iosgl30.o)
[ERROR] 11:01:22.101      (maybe you meant: _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateSubFramebuffer__IILjava_nio_IntBuffer_2IIII, _str_glInvalidateSubFramebuffer_00 , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES30_glInvalidateSubFramebuffer )
[ERROR] 11:01:22.101   "_glCompileShader", referenced from:
[ERROR] 11:01:22.102       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glCompileShader in libgdx.a(iosgl20.o)
[ERROR] 11:01:22.179      (maybe you meant: _str_glCompileShader_00, _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glCompileShader__I , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glCompileShader )
[ERROR] 11:01:22.179   "_glBindRenderbuffer", referenced from:
[ERROR] 11:01:22.179       _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glBindRenderbuffer in libgdx.a(iosgl20.o)
[ERROR] 11:01:22.265      (maybe you meant: _str_glBindRenderbuffer_00, _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glBindRenderbuffer__II , _Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_glBindRenderbuffer )
[ERROR] 11:01:22.278 ld: symbol(s) not found for architecture arm64
[ERROR] 11:01:22.289 clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, -o, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher, -Wl,-filelist,/Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/objects0, -w, -L, /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator, -ObjC, -exported_symbols_list, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/exported_symbols, -Wl,-no_implicit_dylibs, -Wl,-dead_strip, -fPIC, --target=arm64-apple-ios9.0-simulator, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk, -Xlinker, -sectcreate, -Xlinker, __TEXT, -Xlinker, __entitlements, -Xlinker, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/Entitlements-Simulated.plist, -lrobovm-bc, -force_load, /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator/librobovm-rt.a, -lrobovm-debug, -lrobovm-core, -lgc, -lpthread, -ldl, -lm, -lz, -liconv, -lsqlite3, -framework, Foundation, -framework, UIKit, -framework, QuartzCore, -framework, CoreGraphics, -framework, OpenAL, -framework, AudioToolbox, -framework, AVFoundation, -framework, GameController, -force_load, /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator/libgdx.a, -force_load, /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator/libObjectAL.a, -lz, -framework, MobileCoreServices, -Xlinker, -sdk_version, -Xlinker, 15.5, -Xlinker, -rpath, -Xlinker, /usr/lib/swift, -Xlinker, -rpath, -Xlinker, @executable_path/Frameworks, -Xlinker, -rpath, -Xlinker, @loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:409)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:285)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:340)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:279)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:521)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:958)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:277)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

```

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Berstanio** [comment]
Okay, I know what probably the error is.
Could you try to add "<framework>OpenGLES</framework>" to the correct section in the robovm.xml and try it again, this should fix it.
Also, it would be great if you could report whether the arm64 simulator works fine for you!

For the libGDX Contributor: How should the setup work here? The problem is, that in the newer gdx-setup nightly builds the linking against OpenGLES was removed and moved to the backends. However this is not working well, because the fresh setup still creates a project for 1.11.0, which hasn't the linking defined in the backend.

**Comment by ebnbin** [comment]
@Berstanio 

Thanks for the suggestion!!

I tried to add `<framework>OpenGLES</framework>` in `robovm.xml`, and I tried to build the project again in two different macOS devices.

The code works well in an **Intel MacBook**, but still get a problem in an **Apple M1 MacBook**, and the new error log is as follows:

```
[INFO] 16:25:38.436 RoboVM plugin initialized
[INFO] 16:26:07.121 Loading default RoboVM config properties file: /Users/ebnbin/Downloads/test/ios/robovm.properties
[INFO] 16:26:07.122 Loading default RoboVM config file: /Users/ebnbin/Downloads/test/ios/robovm.xml
[INFO] 16:26:07.124 Building executable in /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 16:26:07.124 Installation of app in /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/Downloads/test/core/build/classes/java/main
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/Downloads/test/ios/build/classes/java/main
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-robovm/1.11.0/bedda1c3f9ecf153a9edd245831e620371614d64/gdx-backend-robovm-1.11.0.jar
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.11.0/ffe1206d1004cd9e40027e28964be0fea0399af7/gdx-1.11.0.jar
[INFO] 16:26:07.124 classpath entry: /Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-jnigen-loader/2.3.1/2d472f69243631fbcb3d4c3f93dd2e137a6cb084/gdx-jnigen-loader-2.3.1.jar
[INFO] 16:26:07.124 Using SDK boot classpath
[INFO] 16:26:07.281 Cleaning output dir /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator
[INFO] 16:26:07.307 Compiling classes using 10 threads
[INFO] 16:26:09.297 Compiled 0 classes in 1.99 seconds
[INFO] 16:26:09.299 Linking 4371 classes (ios arm64-simulator release)
[INFO] 16:26:09.435 50905 methods out of 51391 included in the executable
[INFO] 16:26:11.071 Building ios binary /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher
[INFO] 16:26:11.077 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher -Wl,-filelist,/Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/objects0 -w -L /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator -ObjC -exported_symbols_list /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC --target=arm64-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/Entitlements-Simulated.plist -lrobovm-bc -force_load /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework UIKit -framework QuartzCore -framework CoreGraphics -framework OpenAL -framework AudioToolbox -framework AVFoundation -framework GameController -framework OpenGLES -force_load /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator/libgdx.a -force_load /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator/libObjectAL.a -lz -framework MobileCoreServices -Xlinker -sdk_version -Xlinker 15.5 -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks 
[INFO] 16:26:11.077     -Xlinker -rpath -Xlinker @loader_path/Frameworks
[ERROR] 16:26:12.061 ld: unaligned pointer(s) for architecture arm64
[ERROR] 16:26:12.075 clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, -o, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/IOSLauncher, -Wl,-filelist,/Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/objects0, -w, -L, /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator, -ObjC, -exported_symbols_list, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/exported_symbols, -Wl,-no_implicit_dylibs, -Wl,-dead_strip, -fPIC, --target=arm64-apple-ios9.0-simulator, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk, -Xlinker, -sectcreate, -Xlinker, __TEXT, -Xlinker, __entitlements, -Xlinker, /Users/ebnbin/Downloads/test/ios/robovm-build/tmp/ios/ios/arm64-simulator/Entitlements-Simulated.plist, -lrobovm-bc, -force_load, /Users/ebnbin/.robovm-sdks/robovm-2.3.16/lib/vm/ios/arm64-simulator/librobovm-rt.a, -lrobovm-debug, -lrobovm-core, -lgc, -lpthread, -ldl, -lm, -lz, -liconv, -lsqlite3, -framework, Foundation, -framework, UIKit, -framework, QuartzCore, -framework, CoreGraphics, -framework, OpenAL, -framework, AudioToolbox, -framework, AVFoundation, -framework, GameController, -framework, OpenGLES, -force_load, /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator/libgdx.a, -force_load, /Users/ebnbin/.robovm/cache/ios/arm64-simulator/release/Users/ebnbin/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator/libObjectAL.a, -lz, -framework, MobileCoreServices, -Xlinker, -sdk_version, -Xlinker, 15.5, -Xlinker, -rpath, -Xlinker, /usr/lib/swift, -Xlinker, -rpath, -Xlinker, @executable_path/Frameworks, -Xlinker, -rpath, -Xlinker, @loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:409)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:285)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:340)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:279)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:521)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:958)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:277)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

```

So I think the first issue has been fixed, but the project still have some compatibility issues with **Apple M1** chip.

**Comment by Berstanio** [comment]
Are you using macOS Monterey? If I remember correctly I read about similar issues related to macOS 12. 
So it is maybe not libGDX related but robovm, so you might have a better chance asking here: https://gitter.im/MobiVM/robovm

**Comment by ebnbin** [comment]
@Berstanio Okey! Thanks~

**Comment by Berstanio** [comment]
Could you keep the issue open @ebnbin ? The problem with the setup definitely needs to be fixed on libGDX site.

**Comment by obigu** [comment]
> For the libGDX maintainer: How should the setup work here? The problem is, that in the newer gdx-setup nightly builds the linking against OpenGLES was removed and moved to the backends. However this is not working well, because the fresh setup still creates a project for 1.11.0, which hasn't the linking defined in the backend.

Yeah, Snapshot Gdx Setup should use libGDX SNAPSHOT but it doesn't. I think we need to add the OpenGL linking back and remember to remove it on next release (I know it sucks).

**Comment by tommyettinger** [comment]
*coughs*

Versioned releases of gdx-setup...

*coughs loudly*

*hacks up a lung*

*dies*

Maybe you can try https://github.com/tommyettinger/gdx-liftoff and see how that works for you?

**Comment by Berstanio** [comment]
@obigu Okay, I will open a pr. 
To remember to remove this again we could maybe keep this issue open and add it to a 1.11.1 milestone? Or opening a reverting pr already and tag this with the milestone?

**Comment by obigu** [comment]
Yeah, I think a reverting pr with a milestone tag would be best.
