### ISSUE TITLE
Music volume is wrong when calling Gdx.audio.newMusic multiple times in libgdx 1.11.0

### ISSUE THREAD

**Issue by UnbackedFan** [libgdx/libgdx#6890]
#### Issue details
I'm trying to switch between music soundtracks in my game but there is an issue with the music volume once the second soundtrack starts playing.

#### Reproduction steps/code
Here's a sample code that can be run in a dummy project to reproduce the issue. In this case, music "b.mp3" plays lounder than it should. If you comment out Part A, you will hear the difference even though music.getVolume() returns the same value.
```
public class main extends ApplicationAdapter {
	private SpriteBatch batch;
	private Texture image;
	private Music music;
	private AssetManager assetManager;

	@Override
	public void create() {
		batch = new SpriteBatch();
		image = new Texture("libgdx.png");

		//Part A
		music = Gdx.audio.newMusic(Gdx.files.internal("a.mp3"));
		music.setVolume(0.5f);
		music.setLooping(true);
		music.play();
		music.stop();

		//Part B
		music = Gdx.audio.newMusic(Gdx.files.internal("b.mp3"));
		music.setVolume(0.5f);
		music.setLooping(true);
		music.play();


	}

	@Override
	public void render() {
		if(music!= null){
			System.out.println(music.getVolume());
		}
		Gdx.gl.glClearColor(0.15f, 0.15f, 0.2f, 1f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(image, 140, 210);
		batch.end();
	}

	@Override
	public void dispose() {
		music.dispose();
		batch.dispose();
		image.dispose();
	}
}
```

#### Version of libGDX and/or relevant dependencies
Issue found in 1.11.0
I've tested 1.10.0 as well and found no issue.

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by obigu** [comment]
I've tested on a Pixel 3 with 2 different sets of mp3 files and haven't been able to reproduce. Can you please share the files you're using for the test as well as the device model?

**Comment by obigu** [comment]
I can't reproduce with your samples either. My Pixel 3 is on Android 12 so we can probably discard the Android version and my other test device is a Samsung S7.

Do you see any logs?

The only changes to `AndroidMusic` on 1.11.0 I can think of are https://github.com/libgdx/libgdx/pull/6472. Maybe it's the `player.seekTo(0);` that is related to this issue, that line is quite of a mystery and causes other issues. You can run anbd debug your test from source and edit `AndroidMusic` to try to find out the line that causes the problem (If you are not familiar on how to work from source follow this https://libgdx.com/dev/from-source/).

**Comment by UnbackedFan** [comment]
@obigu 
I did some testing and the issue is not the player.seekTo() line but the changes in the DefaultAndroidAudio.java. I reverted the lines that removed MediaPlayer mediaPlayer = new MediaPlayer() so the issue comes from the createMediaPlayer() method.

```
protected MediaPlayer createMediaPlayer() {
		MediaPlayer mediaPlayer = new MediaPlayer();
		if (Build.VERSION.SDK_INT <= 21) {
			mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
		} else {
			mediaPlayer.setAudioAttributes(new AudioAttributes.Builder()
				.setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
				.setUsage(AudioAttributes.USAGE_GAME)
				.build());
		}
		return mediaPlayer;
	}
	```

**Comment by UnbackedFan** [comment]
Removing the .setUsage(AudioAttributes.USAGE_GAME) fixes the issue for me.

**Comment by obigu** [comment]
Welcome to the wonderful world of Android sound!

This is imo a bad implementation on Samsung, the question is if we change it or not. 

According to the docs https://developer.android.com/reference/android/media/AudioAttributes#USAGE_GAME
`Usage value to use when the usage is for game audio.`

The description is pretty generic and probably `USAGE_MEDIA` would also match the way we `Music` in libGDX.
`Usage value to use when the usage is media, such as music, or movie soundtracks.`

One of the reasons it was set to `GAME` (other than because we do games) is that on `SoundPool` I reported a bug myself on Android 10 beta that caused massive lags (https://android-review.googlesource.com/c/platform/frameworks/base/+/1121216/1/media/jni/soundpool/SoundPool.cpp) that was fixed by Google by setting an exception to `AUDIO_USAGE_GAME` so it's definitely needed there.
`if (mSoundPool->attributes()->usage != AUDIO_USAGE_GAME) {`

Does it work for you by setting `USAGE_MEDIA`?

If it does, my only concern is that we change it and other use case breaks on other random device because every manufacturer likes to ~~break~~ customize the OS.

Another option would be to allow overriding the usage via configuration but, even if that may be helpful, we need to have a good default value.

**Comment by UnbackedFan** [comment]
I'm surprised I can't find others complaining about this issue online. I was hoping someone else has a similar issue just to make sure it's not related to some weird setting on my phone. 

I tried USAGE_MEDIA and that also fixes it. Seems to be an issue caused by USAGE_GAME. 

On a side note, I always had weird issues with sounds not always playing at the same volume.  When multiple sounds are playing at the same time the volume is higher than it should be. I tried switching the USAGE_GAME to USAGE_MEDIA in the DefaultAndroidAudio and that also gets rid of the issue but I don't think it's a valid fix.

**Comment by obigu** [comment]
Let's leave it open see if we can get other cases.

Regarding `Sound` if you're going to play multiple sounds at the same time (actually, in all cases except if you need to keep sound ids for some reason) my advice is to use `AsynchronousAndroidAudio` instead.

**Comment by UnbackedFan** [comment]
Yea I guess we can wait a bit and see if others experience the same issues. I've been using AsynchronousAndroidAudio for a while now. Still experiencing the same issue.

**Comment by CivilEngineeringInformation** [comment]
Yes, I suppose we can wait a little longer to see if others are having the same problems. I've been using Asynchronous Android Audio for quite some time. I'm still having the same problem.

**Comment by UnbackedFan** [comment]
Just to add,

I've managed to test on the following devices:

- 2 different Samsung galaxy s20 - Issue found
- Galaxy s20 FE - No Issue
- Galaxy s9 Plus - No Issue
- Galaxy s7 - No Issue

**Comment by obigu** [comment]
Ok, thanks, so everything points to a specific device bug. While we try to fix device specific bugs on our end if the fix is harmless, we can't be sure this would be the case in this case. It's still possible to override `createMediaPlayer()` on client applications that want to "fix it" on their end. I'll close the issue for the time being, feel free to open if there's any development.

**Comment by jonnynaylor92** [comment]
Hi guys was there any follow up to this?

I'm experiencing the same issue of FPS drops on Samsung (Galaxy A22 5G, running Android 11)

I've tried to fixes above, however I don't have AsynchronousAndroidAudio in my LibGDX, and trying to reimplement it doesn't work as there are private/protected fields I can't access in the android backend.

Is there anything you could suggest?

**Comment by obigu** [comment]
This issue has nothing to do with FPS drops. 

You can ask for help on libGDX Discord channel.

**Comment by jonnynaylor92** [comment]
My apologies I had a lot of different issue tabs open that referenced 'AsynchronousAndroidAudio' and performance issues on Android, then I've commented on the wrong one.

I'll make sure to ask on the Discord, thanks!
